# Generated by Django 5.1.3 on 2024-11-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket',
            field=models.BinaryField(),
        ),
    ]
