# Generated by Django 5.1.3 on 2024-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_tickets_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket',
            field=models.FileField(upload_to='tickets'),
        ),
    ]
