# Generated by Django 5.1.3 on 2024-11-09 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_tickets_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ticket',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.BinaryField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tickets')),
            ],
        ),
    ]
