# Generated by Django 5.1.3 on 2024-11-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_tickets_ticket_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticket',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticket_id',
            field=models.IntegerField(auto_created=True, default=1),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
