# Generated by Django 5.1.3 on 2024-11-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_tickets_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
