# Generated by Django 5.1.3 on 2024-11-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_tickets_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='date',
        ),
        migrations.AddField(
            model_name='tickets',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='trip_plan',
            field=models.TextField(null=True),
        ),
    ]
