# Generated by Django 5.1.3 on 2024-11-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_tickets_date_tickets_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='price',
            field=models.TextField(default=0),
        ),
    ]
