# Generated by Django 5.1.3 on 2024-11-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
