# Generated by Django 5.1.3 on 2024-11-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_projectuser_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='countries',
        ),
    ]
