# Generated by Django 5.1.3 on 2026-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_projectuser_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
